name: Java CI with Maven (Bai 8)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Thuê máy ảo Ubuntu của GitHub

    steps:
    - uses: actions/checkout@v4 # Lấy code từ repo của mày bỏ vào máy ảo

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Package with Maven
      # Máy ảo sẽ tự chạy lệnh đóng gói file JAR
      run: mvn -pl bai9.8 clean package

    - name: Run JAR file
      # Chạy thử file đã đóng gói để kiểm tra kết quả
      run: mvn clean package
      
 
